// GENERATED by ores-contracts from both authorities (parity-checked) — do not edit.
// namespace Hhaus.Public
#![allow(dead_code)]

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum AccountKind {
    #[serde(rename = "individual")]
    Individual,
    #[serde(rename = "organization")]
    Organization,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum ClientPlatform {
    #[serde(rename = "browser")]
    Browser,
    #[serde(rename = "desktop")]
    Desktop,
    #[serde(rename = "ios")]
    Ios,
    #[serde(rename = "android")]
    Android,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
pub enum LocationAvailability {
    #[serde(rename = "accepting-reservations")]
    AcceptingReservations,
    #[serde(rename = "waitlist")]
    Waitlist,
    #[serde(rename = "closed")]
    Closed,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct ClientInfo {
    pub install_id: String,
    pub platform: ClientPlatform,
    pub app_version: String,
    pub locale: Option<String>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct IdempotencyKey {
    pub key: String,
    pub minted_at_ms: i64,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct PublicAccountContext {
    pub id: uuid::Uuid,
    pub kind: AccountKind,
    pub display_name: String,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
#[serde(deny_unknown_fields, rename_all = "camelCase")]
pub struct PublicLocation {
    pub slug: String,
    pub display_name: String,
    pub city: String,
    pub country_code: String,
    pub timezone: String,
    pub availability: LocationAvailability,
}
